dist: xenial
language: python
cache: pip
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_b9974129fa9b_key -iv $encrypted_b9974129fa9b_iv
  -in trtravis_key.enc -out ~\/trtravis_key -d
- python -m pip install --upgrade pip
- pip3 install --upgrade pytest
- pip3 install codecov
install:
- pip install -r requirements.txt
script: pytest
deploy:
  provider: script
  script: bash .travis/deploy.sh production
  on:
    branch: master
