# .travis.yml
dist: xenial
language: python
cache: pip
python: 
  - "3.6" 
before_install:
  - python -m pip install --upgrade pip
  - pip3 install --upgrade pytest
  - pip3 install codecov
install:
  - pip install -r requirements.txt
script: pytest